### ISSUE TITLE
Division content => Markdown

### ISSUE THREAD

**Issue by flashadvocate** [ClanAODDev/aod_site_v2#48]
We're in the process of converting documentation on the tracker to a markdown format so it's easier to maintain, accept contributions. We can take a similar approach with the divisional pages. This will be a multi-stage process:

- convert all division content pages to equivalent markdown
  - [x] Battlefield
  - [x] PlanetSide
  - [x] War Thunder
  - [x] Destiny 2
  - [x] World of Warships
  - [x] Call of Duty
  - [x] New World
  - [x] Diablo
  - [x] Skull and Bones
  - [x] Helldivers

- move division markdown content to the divisions model or a separate `DivisionContent` model/table
- Devise publish states (`draft`, `approved`, `published`)
  - Divisions make changes on the tracker, submit those changes, MSGT+ reviews and approves, and then the content gets published

Ideally, an automation process handles converting "approved" content to "published" by way of converting the markdown to a static page. Or we come up with some efficient way of handling markdown => html conversion.

An end goal for the site is to become a thin client that mostly displays the data from the tracker, and we no longer have loose division assets needing to be managed on the site-side of things.

**Comment by manimal-prime** [comment]
When you say division content pages - are you talking about the forums / tracker or both?

**Comment by bashtech** [comment]
> When you say division content pages - are you talking about the forums / tracker or both?

It should be the content located here: https://github.com/ClanAODDev/aod_site_v2/tree/main/resources/views/division/content

**Comment by manimal-prime** [comment]
Ok, so the site - got it! TY!!

**Comment by manimal-prime** [comment]
resolved
